[phases.setup]
aptPkgs = [
  "chromium-browser",
  "chromium-browser-l10n",
  "chromium-codecs-ffmpeg",
  "fonts-liberation",
  "fonts-dejavu",
  "ca-certificates"
]

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/usr/bin/chromium-browser"