'use strict';var aa,ba=typeof Object.create=="function"?Object.create:function(a){function b(){}b.prototype=a;return new b},ca=typeof Object.defineProperties=="function"?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function da(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var ea=da(this);function l(a,b){if(b)a:{var c=ea;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&b!=null&&ca(c,a,{configurable:!0,writable:!0,value:b})}}var fa;
if(typeof Object.setPrototypeOf=="function")fa=Object.setPrototypeOf;else{var ha;a:{var ia={a:!0},ja={};try{ja.__proto__=ia;ha=ja.a;break a}catch(a){}ha=!1}fa=ha?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ka=fa;
function p(a,b){a.prototype=ba(b.prototype);a.prototype.constructor=a;if(ka)ka(a,b);else for(var c in b)if(c!="prototype")if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.ga=b.prototype}function la(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}
function q(a){var b=typeof Symbol!="undefined"&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if(typeof a.length=="number")return{next:la(a)};throw Error(String(a)+" is not an iterable or ArrayLike");}function ma(a){if(!(a instanceof Object))throw new TypeError("Iterator result "+a+" is not an object");}function r(){this.D=!1;this.o=null;this.j=void 0;this.g=1;this.m=this.u=0;this.H=this.i=null}function na(a){if(a.D)throw new TypeError("Generator is already running");a.D=!0}
r.prototype.G=function(a){this.j=a};function oa(a,b){a.i={X:b,isException:!0};a.g=a.u||a.m}r.prototype.getNextAddressJsc=function(){return this.g};r.prototype.getYieldResultJsc=function(){return this.j};r.prototype.return=function(a){this.i={return:a};this.g=this.m};r.prototype["return"]=r.prototype.return;r.prototype.K=function(a){this.i={F:a};this.g=this.m};r.prototype.jumpThroughFinallyBlocks=r.prototype.K;r.prototype.h=function(a,b){this.g=b;return{value:a}};r.prototype.yield=r.prototype.h;
r.prototype.N=function(a,b){a=q(a);var c=a.next();ma(c);if(c.done)this.j=c.value,this.g=b;else return this.o=a,this.h(c.value,b)};r.prototype.yieldAll=r.prototype.N;r.prototype.F=function(a){this.g=a};r.prototype.jumpTo=r.prototype.F;r.prototype.C=function(){this.g=0};r.prototype.jumpToEnd=r.prototype.C;r.prototype.A=function(a,b){this.u=a;b!=void 0&&(this.m=b)};r.prototype.setCatchFinallyBlocks=r.prototype.A;r.prototype.M=function(a){this.u=0;this.m=a||0};r.prototype.setFinallyBlock=r.prototype.M;
r.prototype.B=function(a,b){this.g=a;this.u=b||0};r.prototype.leaveTryBlock=r.prototype.B;r.prototype.v=function(a){this.u=a||0;a=this.i.X;this.i=null;return a};r.prototype.enterCatchBlock=r.prototype.v;r.prototype.I=function(a,b,c){c?this.H[c]=this.i:this.H=[this.i];this.u=a||0;this.m=b||0};r.prototype.enterFinallyBlock=r.prototype.I;
r.prototype.L=function(a,b){b=this.H.splice(b||0)[0];(b=this.i=this.i||b)?b.isException?this.g=this.u||this.m:b.F!=void 0&&this.m<b.F?(this.g=b.F,this.i=null):this.g=this.m:this.g=a};r.prototype.leaveFinallyBlock=r.prototype.L;r.prototype.J=function(a){return new pa(a)};r.prototype.forIn=r.prototype.J;function pa(a){this.i=a;this.g=[];for(var b in a)this.g.push(b);this.g.reverse()}pa.prototype.h=function(){for(;this.g.length>0;){var a=this.g.pop();if(a in this.i)return a}return null};
pa.prototype.getNext=pa.prototype.h;function qa(a){this.g=new r;this.h=a}function ra(a,b){na(a.g);var c=a.g.o;if(c)return sa(a,"return"in c?c["return"]:function(d){return{value:d,done:!0}},b,a.g.return);a.g.return(b);return ta(a)}function sa(a,b,c,d){try{var e=b.call(a.g.o,c);ma(e);if(!e.done)return a.g.D=!1,e;var f=e.value}catch(g){return a.g.o=null,oa(a.g,g),ta(a)}a.g.o=null;d.call(a.g,f);return ta(a)}
function ta(a){for(;a.g.g;)try{var b=a.h(a.g);if(b)return a.g.D=!1,{value:b.value,done:!1}}catch(c){a.g.j=void 0,oa(a.g,c)}a.g.D=!1;if(a.g.i){b=a.g.i;a.g.i=null;if(b.isException)throw b.X;return{value:b.return,done:!0}}return{value:void 0,done:!0}}
function ua(a){this.next=function(b){na(a.g);a.g.o?b=sa(a,a.g.o.next,b,a.g.G):(a.g.G(b),b=ta(a));return b};this.throw=function(b){na(a.g);a.g.o?b=sa(a,a.g.o["throw"],b,a.g.G):(oa(a.g,b),b=ta(a));return b};this.return=function(b){return ra(a,b)};this[Symbol.iterator]=function(){return this}}function va(a){function b(d){return a.next(d)}function c(d){return a.throw(d)}return new Promise(function(d,e){function f(g){g.done?d(g.value):Promise.resolve(g.value).then(b,c).then(f,e)}f(a.next())})}
function t(a){return va(new ua(new qa(a)))}l("Reflect.setPrototypeOf",function(a){return a?a:ka?function(b,c){try{return ka(b,c),!0}catch(d){return!1}}:null});
l("Symbol",function(a){function b(f){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(d+(f||"")+"_"+e++,f)}function c(f,g){this.g=f;ca(this,"description",{configurable:!0,writable:!0,value:g})}if(a)return a;c.prototype.toString=function(){return this.g};var d="jscomp_symbol_"+(Math.random()*1E9>>>0)+"_",e=0;return b});
l("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");ca(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return wa(la(this))}});return a});function wa(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
l("Promise",function(a){function b(g){this.h=0;this.i=void 0;this.g=[];this.u=!1;var h=this.j();try{g(h.resolve,h.reject)}catch(k){h.reject(k)}}function c(){this.g=null}function d(g){return g instanceof b?g:new b(function(h){h(g)})}if(a)return a;c.prototype.h=function(g){if(this.g==null){this.g=[];var h=this;this.i(function(){h.m()})}this.g.push(g)};var e=ea.setTimeout;c.prototype.i=function(g){e(g,0)};c.prototype.m=function(){for(;this.g&&this.g.length;){var g=this.g;this.g=[];for(var h=0;h<g.length;++h){var k=
g[h];g[h]=null;try{k()}catch(m){this.j(m)}}}this.g=null};c.prototype.j=function(g){this.i(function(){throw g;})};b.prototype.j=function(){function g(m){return function(n){k||(k=!0,m.call(h,n))}}var h=this,k=!1;return{resolve:g(this.D),reject:g(this.m)}};b.prototype.D=function(g){if(g===this)this.m(new TypeError("A Promise cannot resolve to itself"));else if(g instanceof b)this.H(g);else{a:switch(typeof g){case "object":var h=g!=null;break a;case "function":h=!0;break a;default:h=!1}h?this.C(g):this.o(g)}};
b.prototype.C=function(g){var h=void 0;try{h=g.then}catch(k){this.m(k);return}typeof h=="function"?this.I(h,g):this.o(g)};b.prototype.m=function(g){this.v(2,g)};b.prototype.o=function(g){this.v(1,g)};b.prototype.v=function(g,h){if(this.h!=0)throw Error("Cannot settle("+g+", "+h+"): Promise already settled in state"+this.h);this.h=g;this.i=h;this.h===2&&this.G();this.B()};b.prototype.G=function(){var g=this;e(function(){if(g.A()){var h=ea.console;typeof h!=="undefined"&&h.error(g.i)}},1)};b.prototype.A=
function(){if(this.u)return!1;var g=ea.CustomEvent,h=ea.Event,k=ea.dispatchEvent;if(typeof k==="undefined")return!0;typeof g==="function"?g=new g("unhandledrejection",{cancelable:!0}):typeof h==="function"?g=new h("unhandledrejection",{cancelable:!0}):(g=ea.document.createEvent("CustomEvent"),g.initCustomEvent("unhandledrejection",!1,!0,g));g.promise=this;g.reason=this.i;return k(g)};b.prototype.B=function(){if(this.g!=null){for(var g=0;g<this.g.length;++g)f.h(this.g[g]);this.g=null}};var f=new c;
b.prototype.H=function(g){var h=this.j();g.R(h.resolve,h.reject)};b.prototype.I=function(g,h){var k=this.j();try{g.call(h,k.resolve,k.reject)}catch(m){k.reject(m)}};b.prototype.then=function(g,h){function k(y,A){return typeof y=="function"?function(G){try{m(y(G))}catch(D){n(D)}}:A}var m,n,w=new b(function(y,A){m=y;n=A});this.R(k(g,m),k(h,n));return w};b.prototype.catch=function(g){return this.then(void 0,g)};b.prototype.R=function(g,h){function k(){switch(m.h){case 1:g(m.i);break;case 2:h(m.i);break;
default:throw Error("Unexpected state: "+m.h);}}var m=this;this.g==null?f.h(k):this.g.push(k);this.u=!0};b.resolve=d;b.reject=function(g){return new b(function(h,k){k(g)})};b.race=function(g){return new b(function(h,k){for(var m=q(g),n=m.next();!n.done;n=m.next())d(n.value).R(h,k)})};b.all=function(g){var h=q(g),k=h.next();return k.done?d([]):new b(function(m,n){function w(G){return function(D){y[G]=D;A--;A==0&&m(y)}}var y=[],A=0;do y.push(void 0),A++,d(k.value).R(w(y.length-1),n),k=h.next();while(!k.done)})};
return b});l("Object.setPrototypeOf",function(a){return a||ka});function u(a,b){return Object.prototype.hasOwnProperty.call(a,b)}var xa=typeof Object.assign=="function"?Object.assign:function(a,b){if(a==null)throw new TypeError("No nullish arg");a=Object(a);for(var c=1;c<arguments.length;c++){var d=arguments[c];if(d)for(var e in d)u(d,e)&&(a[e]=d[e])}return a};l("Object.assign",function(a){return a||xa});
l("WeakMap",function(a){function b(k){this.g=(h+=Math.random()+1).toString();if(k){k=q(k);for(var m;!(m=k.next()).done;)m=m.value,this.set(m[0],m[1])}}function c(){}function d(k){var m=typeof k;return m==="object"&&k!==null||m==="function"}function e(k){if(!u(k,g)){var m=new c;ca(k,g,{value:m})}}function f(k){var m=Object[k];m&&(Object[k]=function(n){if(n instanceof c)return n;Object.isExtensible(n)&&e(n);return m(n)})}if(function(){if(!a||!Object.seal)return!1;try{var k=Object.seal({}),m=Object.seal({}),
n=new a([[k,2],[m,3]]);if(n.get(k)!=2||n.get(m)!=3)return!1;n.delete(k);n.set(m,4);return!n.has(k)&&n.get(m)==4}catch(w){return!1}}())return a;var g="$jscomp_hidden_"+Math.random();f("freeze");f("preventExtensions");f("seal");var h=0;b.prototype.set=function(k,m){if(!d(k))throw Error("Invalid WeakMap key");e(k);if(!u(k,g))throw Error("WeakMap key fail: "+k);k[g][this.g]=m;return this};b.prototype.get=function(k){return d(k)&&u(k,g)?k[g][this.g]:void 0};b.prototype.has=function(k){return d(k)&&u(k,
g)&&u(k[g],this.g)};b.prototype.delete=function(k){return d(k)&&u(k,g)&&u(k[g],this.g)?delete k[g][this.g]:!1};return b});
l("Map",function(a){function b(){var h={};return h.previous=h.next=h.head=h}function c(h,k){var m=h[1];return wa(function(){if(m){for(;m.head!=h[1];)m=m.previous;for(;m.next!=m.head;)return m=m.next,{done:!1,value:k(m)};m=null}return{done:!0,value:void 0}})}function d(h,k){var m=k&&typeof k;m=="object"||m=="function"?f.has(k)?m=f.get(k):(m=""+ ++g,f.set(k,m)):m="p_"+k;var n=h[0][m];if(n&&u(h[0],m))for(h=0;h<n.length;h++){var w=n[h];if(k!==k&&w.key!==w.key||k===w.key)return{id:m,list:n,index:h,entry:w}}return{id:m,
list:n,index:-1,entry:void 0}}function e(h){this[0]={};this[1]=b();this.size=0;if(h){h=q(h);for(var k;!(k=h.next()).done;)k=k.value,this.set(k[0],k[1])}}if(function(){if(!a||typeof a!="function"||!a.prototype.entries||typeof Object.seal!="function")return!1;try{var h=Object.seal({x:4}),k=new a(q([[h,"s"]]));if(k.get(h)!="s"||k.size!=1||k.get({x:4})||k.set({x:4},"t")!=k||k.size!=2)return!1;var m=k.entries(),n=m.next();if(n.done||n.value[0]!=h||n.value[1]!="s")return!1;n=m.next();return n.done||n.value[0].x!=
4||n.value[1]!="t"||!m.next().done?!1:!0}catch(w){return!1}}())return a;var f=new WeakMap;e.prototype.set=function(h,k){h=h===0?0:h;var m=d(this,h);m.list||(m.list=this[0][m.id]=[]);m.entry?m.entry.value=k:(m.entry={next:this[1],previous:this[1].previous,head:this[1],key:h,value:k},m.list.push(m.entry),this[1].previous.next=m.entry,this[1].previous=m.entry,this.size++);return this};e.prototype.delete=function(h){h=d(this,h);return h.entry&&h.list?(h.list.splice(h.index,1),h.list.length||delete this[0][h.id],
h.entry.previous.next=h.entry.next,h.entry.next.previous=h.entry.previous,h.entry.head=null,this.size--,!0):!1};e.prototype.clear=function(){this[0]={};this[1]=this[1].previous=b();this.size=0};e.prototype.has=function(h){return!!d(this,h).entry};e.prototype.get=function(h){return(h=d(this,h).entry)&&h.value};e.prototype.entries=function(){return c(this,function(h){return[h.key,h.value]})};e.prototype.keys=function(){return c(this,function(h){return h.key})};e.prototype.values=function(){return c(this,
function(h){return h.value})};e.prototype.forEach=function(h,k){for(var m=this.entries(),n;!(n=m.next()).done;)n=n.value,h.call(k,n[1],n[0],this)};e.prototype[Symbol.iterator]=e.prototype.entries;var g=0;return e});
l("Array.from",function(a){return a?a:function(b,c,d){c=c!=null?c:function(h){return h};var e=[],f=typeof Symbol!="undefined"&&Symbol.iterator&&b[Symbol.iterator];if(typeof f=="function"){b=f.call(b);for(var g=0;!(f=b.next()).done;)e.push(c.call(d,f.value,g++))}else for(f=b.length,g=0;g<f;g++)e.push(c.call(d,b[g],g));return e}});l("Object.entries",function(a){return a?a:function(b){var c=[],d;for(d in b)u(b,d)&&c.push([d,b[d]]);return c}});
l("Number.isFinite",function(a){return a?a:function(b){return typeof b!=="number"?!1:!isNaN(b)&&b!==Infinity&&b!==-Infinity}});l("Number.MAX_SAFE_INTEGER",function(){return 9007199254740991});l("Number.MIN_SAFE_INTEGER",function(){return-9007199254740991});l("Number.isInteger",function(a){return a?a:function(b){return Number.isFinite(b)?b===Math.floor(b):!1}});l("Number.isSafeInteger",function(a){return a?a:function(b){return Number.isInteger(b)&&Math.abs(b)<=Number.MAX_SAFE_INTEGER}});
l("Object.is",function(a){return a?a:function(b,c){return b===c?b!==0||1/b===1/c:b!==b&&c!==c}});l("Array.prototype.includes",function(a){return a?a:function(b,c){var d=this;d instanceof String&&(d=String(d));var e=d.length;c=c||0;for(c<0&&(c=Math.max(c+e,0));c<e;c++){var f=d[c];if(f===b||Object.is(f,b))return!0}return!1}});
l("String.prototype.includes",function(a){return a?a:function(b,c){if(this==null)throw new TypeError("The 'this' value for String.prototype.includes must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype.includes must not be a regular expression");return this.indexOf(b,c||0)!==-1}});
function ya(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var f=c++;return{value:b(f,a[f]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e}l("Array.prototype.entries",function(a){return a?a:function(){return ya(this,function(b,c){return[b,c]})}});l("Math.trunc",function(a){return a?a:function(b){b=Number(b);if(isNaN(b)||b===Infinity||b===-Infinity||b===0)return b;var c=Math.floor(Math.abs(b));return b<0?-c:c}});
l("Array.prototype.find",function(a){return a?a:function(b,c){a:{var d=this;d instanceof String&&(d=String(d));for(var e=d.length,f=0;f<e;f++){var g=d[f];if(b.call(c,g,f,d)){b=g;break a}}b=void 0}return b}});l("Number.isNaN",function(a){return a?a:function(b){return typeof b==="number"&&isNaN(b)}});/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var za=this||self;function Aa(a,b){a:{var c=["CLOSURE_FLAGS"];for(var d=za,e=0;e<c.length;e++)if(d=d[c[e]],d==null){c=null;break a}c=d}a=c&&c[a];return a!=null?a:b}function Ba(a){return a};var Ca=Aa(610401301,!1),Da=Aa(748402147,!0),Ea=Aa(824648567,!0);function Fa(){return typeof BigInt==="function"};function Ga(a){a.ca=!0;return a};var Ha=Ga(function(a){return typeof a==="number"}),Ia=Ga(function(a){return typeof a==="string"}),Ja=Ga(function(a){return typeof a==="boolean"});var Ka=typeof za.BigInt==="function"&&typeof za.BigInt(0)==="bigint";function La(a){var b=a;if(Ia(b)){if(!/^\s*(?:-?[1-9]\d*|0)?\s*$/.test(b))throw Error(String(b));}else if(Ha(b)&&!Number.isSafeInteger(b))throw Error(String(b));return Ka?BigInt(a):a=Ja(a)?a?"1":"0":Ia(a)?a.trim()||"0":String(a)}var Ra=Ga(function(a){return Ka?a>=Ma&&a<=Na:a[0]==="-"?Oa(a,Pa):Oa(a,Qa)}),Pa=Number.MIN_SAFE_INTEGER.toString(),Ma=Ka?BigInt(Number.MIN_SAFE_INTEGER):void 0,Qa=Number.MAX_SAFE_INTEGER.toString(),Na=Ka?BigInt(Number.MAX_SAFE_INTEGER):void 0;
function Oa(a,b){if(a.length>b.length)return!1;if(a.length<b.length||a===b)return!0;for(var c=0;c<a.length;c++){var d=a[c],e=b[c];if(d>e)return!1;if(d<e)return!0}};var Sa=typeof Uint8Array.prototype.slice==="function",v=0,x=0,Ta;function Ua(a){var b=a>>>0;v=b;x=(a-b)/4294967296>>>0}function Va(a){if(a<0){Ua(-a);var b=q(Wa(v,x));a=b.next().value;b=b.next().value;v=a>>>0;x=b>>>0}else Ua(a)}function Xa(a){var b=Ta||(Ta=new DataView(new ArrayBuffer(8)));b.setFloat32(0,+a,!0);x=0;v=b.getUint32(0,!0)}function Ya(a){var b=Ta||(Ta=new DataView(new ArrayBuffer(8)));b.setFloat64(0,+a,!0);v=b.getUint32(0,!0);x=b.getUint32(4,!0)}
function Za(a,b){var c=b*4294967296+(a>>>0);return Number.isSafeInteger(c)?c:$a(a,b)}function ab(a,b){return La(Fa()?BigInt.asUintN(64,(BigInt(b>>>0)<<BigInt(32))+BigInt(a>>>0)):$a(a,b))}function bb(a,b){var c=b&2147483648;c&&(a=~a+1>>>0,b=~b>>>0,a==0&&(b=b+1>>>0));a=Za(a,b);return typeof a==="number"?c?-a:a:c?"-"+a:a}function cb(a,b){return Fa()?La(BigInt.asIntN(64,(BigInt.asUintN(32,BigInt(b))<<BigInt(32))+BigInt.asUintN(32,BigInt(a)))):La(db(a,b))}
function $a(a,b){b>>>=0;a>>>=0;if(b<=2097151)var c=""+(4294967296*b+a);else Fa()?c=""+(BigInt(b)<<BigInt(32)|BigInt(a)):(c=(a>>>24|b<<8)&16777215,b=b>>16&65535,a=(a&16777215)+c*6777216+b*6710656,c+=b*8147497,b*=2,a>=1E7&&(c+=a/1E7>>>0,a%=1E7),c>=1E7&&(b+=c/1E7>>>0,c%=1E7),c=b+eb(c)+eb(a));return c}function eb(a){a=String(a);return"0000000".slice(a.length)+a}
function db(a,b){b&2147483648?Fa()?a=""+(BigInt(b|0)<<BigInt(32)|BigInt(a>>>0)):(b=q(Wa(a,b)),a=b.next().value,b=b.next().value,a="-"+$a(a,b)):a=$a(a,b);return a}
function fb(a){if(a.length<16)Va(Number(a));else if(Fa())a=BigInt(a),v=Number(a&BigInt(4294967295))>>>0,x=Number(a>>BigInt(32)&BigInt(4294967295));else{var b=+(a[0]==="-");x=v=0;for(var c=a.length,d=b,e=(c-b)%6+b;e<=c;d=e,e+=6)d=Number(a.slice(d,e)),x*=1E6,v=v*1E6+d,v>=4294967296&&(x+=Math.trunc(v/4294967296),x>>>=0,v>>>=0);b&&(b=q(Wa(v,x)),a=b.next().value,b=b.next().value,v=a,x=b)}}function Wa(a,b){b=~b;a?a=~a+1:b+=1;return[a,b]};function gb(a,b){this.h=a>>>0;this.g=b>>>0}function hb(a){return a.h===0?new gb(0,1+~a.g):new gb(~a.h+1,~a.g)}function ib(a){a=BigInt.asUintN(64,a);return new gb(Number(a&BigInt(4294967295)),Number(a>>BigInt(32)))}function jb(a){if(!a)return kb||(kb=new gb(0,0));if(!/^\d+$/.test(a))return null;fb(a);return new gb(v,x)}var kb;function lb(a,b){this.h=a>>>0;this.g=b>>>0}function mb(a){a=BigInt.asUintN(64,a);return new lb(Number(a&BigInt(4294967295)),Number(a>>BigInt(32)))}
function nb(a){if(!a)return ob||(ob=new lb(0,0));if(!/^-?\d+$/.test(a))return null;fb(a);return new lb(v,x)}var ob;function pb(){throw Error("Invalid UTF8");}function qb(a,b){b=String.fromCharCode.apply(null,b);return a==null?b:a+b}var rb=void 0,sb,tb=typeof TextDecoder!=="undefined",ub,vb=typeof String.prototype.isWellFormed==="function",wb=typeof TextEncoder!=="undefined";
function xb(a){var b=!1;b=b===void 0?!1:b;if(wb){if(b&&(vb?!a.isWellFormed():/(?:[^\uD800-\uDBFF]|^)[\uDC00-\uDFFF]|[\uD800-\uDBFF](?![\uDC00-\uDFFF])/.test(a)))throw Error("Found an unpaired surrogate");a=(ub||(ub=new TextEncoder)).encode(a)}else{for(var c=0,d=new Uint8Array(3*a.length),e=0;e<a.length;e++){var f=a.charCodeAt(e);if(f<128)d[c++]=f;else{if(f<2048)d[c++]=f>>6|192;else{if(f>=55296&&f<=57343){if(f<=56319&&e<a.length){var g=a.charCodeAt(++e);if(g>=56320&&g<=57343){f=(f-55296)*1024+g-56320+
65536;d[c++]=f>>18|240;d[c++]=f>>12&63|128;d[c++]=f>>6&63|128;d[c++]=f&63|128;continue}else e--}if(b)throw Error("Found an unpaired surrogate");f=65533}d[c++]=f>>12|224;d[c++]=f>>6&63|128}d[c++]=f&63|128}}a=c===d.length?d:d.subarray(0,c)}return a};function yb(a){za.setTimeout(function(){throw a;},0)};function zb(){var a=za.navigator;return a&&(a=a.userAgent)?a:""}var Ab,Bb=za.navigator;Ab=Bb?Bb.userAgentData||null:null;var Cb={},Db=null;function Eb(a){var b=a.length,c=b*3/4;c%3?c=Math.floor(c):"=.".indexOf(a[b-1])!=-1&&(c="=.".indexOf(a[b-2])!=-1?c-2:c-1);var d=new Uint8Array(c),e=0;Fb(a,function(f){d[e++]=f});return e!==c?d.subarray(0,e):d}
function Fb(a,b){function c(k){for(;d<a.length;){var m=a.charAt(d++),n=Db[m];if(n!=null)return n;if(!/^[\s\xa0]*$/.test(m))throw Error("Unknown base64 encoding at char: "+m);}return k}Gb();for(var d=0;;){var e=c(-1),f=c(0),g=c(64),h=c(64);if(h===64&&e===-1)break;b(e<<2|f>>4);g!=64&&(b(f<<4&240|g>>2),h!=64&&b(g<<6&192|h))}}
function Gb(){if(!Db){Db={};for(var a="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),b=["+/=","+/","-_=","-_.","-_"],c=0;c<5;c++){var d=a.concat(b[c].split(""));Cb[c]=d;for(var e=0;e<d.length;e++){var f=d[e];Db[f]===void 0&&(Db[f]=e)}}}};var Hb=typeof Uint8Array!=="undefined",Ib=!(Ca&&Ab&&Ab.brands.length>0?0:zb().indexOf("Trident")!=-1||zb().indexOf("MSIE")!=-1)&&typeof btoa==="function",Jb=/[-_.]/g,Kb={"-":"+",_:"/",".":"="};function Lb(a){return Kb[a]||""}function Mb(a){if(!Ib)return Eb(a);a=Jb.test(a)?a.replace(Jb,Lb):a;a=atob(a);for(var b=new Uint8Array(a.length),c=0;c<a.length;c++)b[c]=a.charCodeAt(c);return b}var Nb={};function Ob(a,b){Pb(b);this.g=a;if(a!=null&&a.length===0)throw Error("ByteString should be constructed with non-empty values");}function Qb(){return Rb||(Rb=new Ob(null,Nb))}function Tb(a){Pb(Nb);var b=a.g;b=b==null||Hb&&b!=null&&b instanceof Uint8Array?b:typeof b==="string"?Mb(b):null;return b==null?b:a.g=b}var Rb;function Pb(a){if(a!==Nb)throw Error("illegal external caller");};function Ub(a,b,c){this.buffer=a;if(c&&!b)throw Error();this.g=b}
function Vb(a,b){if(typeof a==="string")return new Ub(Mb(a),b);if(Array.isArray(a))return new Ub(new Uint8Array(a),b);if(a.constructor===Uint8Array)return new Ub(a,!1);if(a.constructor===ArrayBuffer)return a=new Uint8Array(a),new Ub(a,!1);if(a.constructor===Ob)return b=Tb(a)||new Uint8Array(0),new Ub(b,!0,a);if(a instanceof Uint8Array)return a=a.constructor===Uint8Array?a:new Uint8Array(a.buffer,a.byteOffset,a.byteLength),new Ub(a,!1);throw Error();};function Wb(a,b,c,d){this.h=null;this.m=!1;this.g=this.i=this.j=0;this.init(a,b,c,d)}Wb.prototype.init=function(a,b,c,d){var e=d===void 0?{}:d;d=e.P===void 0?!1:e.P;e=e.S===void 0?!1:e.S;this.P=d;this.S=e;a&&(a=Vb(a,this.S),this.h=a.buffer,this.m=a.g,this.j=b||0,this.i=c!==void 0?this.j+c:this.h.length,this.g=this.j)};Wb.prototype.clear=function(){this.h=null;this.m=!1;this.g=this.i=this.j=0;this.P=!1};
function Xb(a,b){var c=0,d=0,e=0,f=a.h,g=a.g;do{var h=f[g++];c|=(h&127)<<e;e+=7}while(e<32&&h&128);if(e>32)for(d|=(h&127)>>4,e=3;e<32&&h&128;e+=7)h=f[g++],d|=(h&127)<<e;Yb(a,g);if(!(h&128))return b(c>>>0,d>>>0);throw Error();}function Yb(a,b){a.g=b;if(b>a.i)throw Error();}
function Zb(a){var b=a.h,c=a.g,d=b[c++],e=d&127;if(d&128&&(d=b[c++],e|=(d&127)<<7,d&128&&(d=b[c++],e|=(d&127)<<14,d&128&&(d=b[c++],e|=(d&127)<<21,d&128&&(d=b[c++],e|=d<<28,d&128&&b[c++]&128&&b[c++]&128&&b[c++]&128&&b[c++]&128&&b[c++]&128)))))throw Error();Yb(a,c);return e}function $b(a){return Zb(a)>>>0}function ac(a){a=$b(a);return a>>>1^-(a&1)}function bc(a){return Xb(a,bb)}function cc(a){return Xb(a,cb)}
function dc(a){var b=a.h,c=a.g,d=b[c],e=b[c+1],f=b[c+2];b=b[c+3];Yb(a,a.g+4);return(d<<0|e<<8|f<<16|b<<24)>>>0}function ec(a){var b=dc(a);a=(b>>31)*2+1;var c=b>>>23&255;b&=8388607;return c==255?b?NaN:a*Infinity:c==0?a*1.401298464324817E-45*b:a*Math.pow(2,c-150)*(b+8388608)}function fc(a){var b=dc(a),c=dc(a);a=(c>>31)*2+1;var d=c>>>20&2047;b=4294967296*(c&1048575)+b;return d==2047?b?NaN:a*Infinity:d==0?a*4.9E-324*b:a*Math.pow(2,d-1075)*(b+4503599627370496)}
function hc(a){for(var b=0,c=a.g,d=c+10,e=a.h;c<d;){var f=e[c++];b|=f;if((f&128)===0)return Yb(a,c),!!(b&127)}throw Error();}function ic(a){return Zb(a)}function jc(a,b){if(b<0)throw Error();var c=a.g;b=c+b;if(b>a.i)throw Error();a.g=b;return c}function kc(a,b){if(b==0)return Qb();var c=jc(a,b);a.P&&a.m?c=a.h.subarray(c,c+b):(a=a.h,b=c+b,c=c===b?new Uint8Array(0):Sa?a.slice(c,b):new Uint8Array(a.subarray(c,b)));return c.length==0?Qb():new Ob(c,Nb)}var lc=[],mc=void 0;function nc(){this.g=[]}nc.prototype.length=function(){return this.g.length};nc.prototype.end=function(){var a=this.g;this.g=[];return a};function oc(a,b,c){for(;c>0||b>127;)a.g.push(b&127|128),b=(b>>>7|c<<25)>>>0,c>>>=7;a.g.push(b)}function pc(a,b){for(;b>127;)a.g.push(b&127|128),b>>>=7;a.g.push(b)}function qc(a,b){if(b>=0)pc(a,b);else{for(var c=0;c<9;c++)a.g.push(b&127|128),b>>=7;a.g.push(1)}}function z(a,b){a.g.push(b>>>0&255);a.g.push(b>>>8&255);a.g.push(b>>>16&255);a.g.push(b>>>24&255)};function rc(a,b,c,d){if(lc.length){var e=lc.pop();e.init(a,b,c,d);a=e}else a=new Wb(a,b,c,d);this.h=a;this.j=this.h.g;this.g=this.i=-1;this.setOptions(d)}rc.prototype.setOptions=function(a){a=a===void 0?{}:a;this.U=a.U===void 0?!1:a.U};function sc(a,b,c,d){if(tc.length){var e=tc.pop();e.setOptions(d);e.h.init(a,b,c,d);return e}return new rc(a,b,c,d)}function uc(a){a.h.clear();a.i=-1;a.g=-1;tc.length<100&&tc.push(a)}
function vc(a){var b=a.h;if(b.g==b.i)return!1;a.j=a.h.g;var c=$b(a.h);b=c>>>3;c&=7;if(!(c>=0&&c<=5))throw Error();if(b<1)throw Error();a.i=b;a.g=c;return!0}function wc(a){switch(a.g){case 0:a.g!=0?wc(a):hc(a.h);break;case 1:a=a.h;Yb(a,a.g+8);break;case 2:if(a.g!=2)wc(a);else{var b=$b(a.h);a=a.h;Yb(a,a.g+b)}break;case 5:a=a.h;Yb(a,a.g+4);break;case 3:b=a.i;do{if(!vc(a))throw Error();if(a.g==4){if(a.i!=b)throw Error();break}wc(a)}while(1);break;default:throw Error();}}
function xc(a,b,c){var d=a.h.i,e=$b(a.h);e=a.h.g+e;var f=e-d;f<=0&&(a.h.i=e,c(b,a,void 0,void 0,void 0),f=e-a.h.g);if(f)throw Error();a.h.g=e;a.h.i=d;return b}
function yc(a){var b=$b(a.h);a=a.h;var c=jc(a,b);a=a.h;if(tb){var d=a,e;(e=sb)||(e=sb=new TextDecoder("utf-8",{fatal:!0}));b=c+b;d=c===0&&b===d.length?d:d.subarray(c,b);try{var f=e.decode(d)}catch(m){if(rb===void 0){try{e.decode(new Uint8Array([128]))}catch(n){}try{e.decode(new Uint8Array([97])),rb=!0}catch(n){rb=!1}}!rb&&(sb=void 0);throw m;}}else{f=c;b=f+b;c=[];for(var g=null,h,k;f<b;)h=a[f++],h<128?c.push(h):h<224?f>=b?pb():(k=a[f++],h<194||(k&192)!==128?(f--,pb()):c.push((h&31)<<6|k&63)):h<240?
f>=b-1?pb():(k=a[f++],(k&192)!==128||h===224&&k<160||h===237&&k>=160||((e=a[f++])&192)!==128?(f--,pb()):c.push((h&15)<<12|(k&63)<<6|e&63)):h<=244?f>=b-2?pb():(k=a[f++],(k&192)!==128||(h<<28)+(k-144)>>30!==0||((e=a[f++])&192)!==128||((d=a[f++])&192)!==128?(f--,pb()):(h=(h&7)<<18|(k&63)<<12|(e&63)<<6|d&63,h-=65536,c.push((h>>10&1023)+55296,(h&1023)+56320))):pb(),c.length>=8192&&(g=qb(g,c),c.length=0);f=qb(g,c)}return f}function zc(a){var b=$b(a.h);return kc(a.h,b)}
function Ac(a,b,c){var d=$b(a.h);for(d=a.h.g+d;a.h.g<d;)c.push(b(a.h))}var tc=[];function Bc(){this.i=[];this.h=0;this.g=new nc}function Cc(a,b){b.length!==0&&(a.i.push(b),a.h+=b.length)}function Dc(a,b){B(a,b,2);b=a.g.end();Cc(a,b);b.push(a.h);return b}function Ec(a,b){var c=b.pop();for(c=a.h+a.g.length()-c;c>127;)b.push(c&127|128),c>>>=7,a.h++;b.push(c);a.h++}function B(a,b,c){pc(a.g,b*8+c)}function Fc(a,b,c){c!=null&&(c=parseInt(c,10),B(a,b,0),qc(a.g,c))}function Gc(a,b,c){B(a,b,2);pc(a.g,c.length);Cc(a,a.g.end());Cc(a,c)}
function Hc(a,b,c,d){c!=null&&(b=Dc(a,b),d(c,a),Ec(a,b))}function Ic(a){switch(typeof a){case "string":a.length&&a[0]==="-"?jb(a.substring(1)):jb(a)}};var Jc=typeof Symbol==="function"&&typeof Symbol()==="symbol";function Kc(a,b,c){return typeof Symbol==="function"&&typeof Symbol()==="symbol"?(c===void 0?0:c)&&Symbol.for&&a?Symbol.for(a):a!=null?Symbol(a):Symbol():b}var Lc=Kc("jas",void 0,!0),Mc=Kc(void 0,"1oa"),Nc=Kc(void 0,Symbol()),Oc=Kc(void 0,"0ubs"),Pc=Kc(void 0,"0ubsb"),Qc=Kc(void 0,"0actk"),Rc=Kc("m_m","da",!0);var Sc={ba:{value:0,configurable:!0,writable:!0,enumerable:!1}},Tc=Object.defineProperties,C=Jc?Lc:"ba",Uc,Vc=[];E(Vc,7);Uc=Object.freeze(Vc);function Wc(a,b){Jc||C in a||Tc(a,Sc);a[C]|=b}function E(a,b){Jc||C in a||Tc(a,Sc);a[C]=b}function Xc(a){Wc(a,8192);return a};var Yc={};function Zc(a,b){return b===void 0?a.g!==$c&&!!(2&(a.l[C]|0)):!!(2&b)&&a.g!==$c}var $c={};function ad(a,b,c){var d=b&128?0:-1,e=a.length,f;if(f=!!e)f=a[e-1],f=f!=null&&typeof f==="object"&&f.constructor===Object;var g=e+(f?-1:0);for(b=b&128?1:0;b<g;b++)c(b-d,a[b]);if(f){a=a[e-1];for(var h in a)!isNaN(h)&&c(+h,a[h])}}var bd={};function cd(a){return a&128?bd:void 0};function dd(a){return a};var ed=void 0;function fd(a,b){if(a!=null){var c;var d=(c=ed)!=null?c:ed={};c=d[a]||0;c>=b||(d[a]=c+1,a=Error(),a.__closure__error__context__984382||(a.__closure__error__context__984382={}),a.__closure__error__context__984382.severity="incident",yb(a))}};function gd(a){return Array.prototype.slice.call(a)};var ld=typeof BigInt==="function"?BigInt.asIntN:void 0,md=typeof BigInt==="function"?BigInt.asUintN:void 0,nd=Number.isSafeInteger,od=Number.isFinite,pd=Math.trunc;function qd(a){if(a!=null&&typeof a!=="number")throw Error("Value of float/double field must be a number, found "+typeof a+": "+a);return a}function rd(a){if(a==null||typeof a==="number")return a;if(a==="NaN"||a==="Infinity"||a==="-Infinity")return Number(a)}
function sd(a){if(a==null||typeof a==="boolean")return a;if(typeof a==="number")return!!a}var td=/^-?([1-9][0-9]*|0)(\.[0-9]+)?$/;function ud(a){switch(typeof a){case "bigint":return!0;case "number":return od(a);case "string":return td.test(a);default:return!1}}function vd(a){if(a==null)return a;if(typeof a==="string"&&a)a=+a;else if(typeof a!=="number")return;return od(a)?a|0:void 0}
function wd(a){if(a==null)return a;if(typeof a==="string"&&a)a=+a;else if(typeof a!=="number")return;return od(a)?a>>>0:void 0}
function xd(a){if(a==null)return a;var b=typeof a;if(b==="bigint")return String(ld(64,a));if(ud(a)){if(b==="string")return b=pd(Number(a)),nd(b)?a=String(b):(b=a.indexOf("."),b!==-1&&(a=a.substring(0,b)),b=a.length,(a[0]==="-"?b<20||b===20&&a<="-9223372036854775808":b<19||b===19&&a<="9223372036854775807")||(fb(a),a=db(v,x))),a;if(b==="number")return a=pd(a),nd(a)||(Va(a),a=bb(v,x)),a}}
function yd(a){if(a==null)return a;var b=typeof a;if(b==="bigint")return String(md(64,a));if(ud(a)){if(b==="string")return b=pd(Number(a)),nd(b)&&b>=0?a=String(b):(b=a.indexOf("."),b!==-1&&(a=a.substring(0,b)),a[0]==="-"?b=!1:(b=a.length,b=b<20?!0:b===20&&a<="18446744073709551615"),b||(fb(a),a=$a(v,x))),a;if(b==="number")return a=pd(a),a>=0&&nd(a)||(Va(a),a=Za(v,x)),a}}function zd(a){if(a==null||typeof a=="string"||a instanceof Ob)return a}
function Ad(a){if(a!=null&&typeof a!=="string")throw Error();return a}function Bd(a){return a==null||typeof a==="string"?a:void 0};function Cd(a){var b=Ba(Nc);return b?a[b]:void 0}function Dd(){}function Ed(a,b){for(var c in a)!isNaN(c)&&b(a,+c,a[c])}function Fd(a){var b=new Dd;Ed(a,function(c,d,e){b[d]=gd(e)});b.g=a.g;return b}function Gd(a,b){b<100||fd(Oc,1)};function Hd(a,b,c,d){var e=d!==void 0;d=!!d;var f=Ba(Nc),g;!e&&Jc&&f&&(g=a[f])&&Ed(g,Gd);f=[];var h=a.length;g=4294967295;var k=!1,m=!!(b&64),n=m?b&128?0:-1:void 0;if(!(b&1)){var w=h&&a[h-1];w!=null&&typeof w==="object"&&w.constructor===Object?(h--,g=h):w=void 0;if(m&&!(b&128)&&!e){k=!0;var y;g=((y=Id)!=null?y:dd)(g-n,n,a,w,void 0)+n}}b=void 0;for(y=0;y<h;y++){var A=a[y];if(A!=null&&(A=c(A,d))!=null)if(m&&y>=g){var G=y-n,D=void 0;((D=b)!=null?D:b={})[G]=A}else f[y]=A}if(w)for(var T in w)h=w[T],h!=
null&&(h=c(h,d))!=null&&(y=+T,A=void 0,m&&!Number.isNaN(y)&&(A=y+n)<g?f[A]=h:(y=void 0,((y=b)!=null?y:b={})[T]=h));b&&(k?f.push(b):f[g]=b);e&&Ba(Nc)&&(a=Cd(a))&&a instanceof Dd&&(f[Nc]=Fd(a));return f}
function Jd(a){switch(typeof a){case "number":return Number.isFinite(a)?a:""+a;case "bigint":return Ra(a)?Number(a):""+a;case "boolean":return a?1:0;case "object":if(Array.isArray(a)){var b=a[C]|0;return a.length===0&&b&1?void 0:Hd(a,b,Jd)}if(a!=null&&a[Rc]===Yc)return Kd(a);if(a instanceof Ob){b=a.g;if(b==null)a="";else if(typeof b==="string")a=b;else{if(Ib){for(var c="",d=0,e=b.length-10240;d<e;)c+=String.fromCharCode.apply(null,b.subarray(d,d+=10240));c+=String.fromCharCode.apply(null,d?b.subarray(d):
b);b=btoa(c)}else{c===void 0&&(c=0);Gb();c=Cb[c];d=Array(Math.floor(b.length/3));e=c[64]||"";for(var f=0,g=0;f<b.length-2;f+=3){var h=b[f],k=b[f+1],m=b[f+2],n=c[h>>2];h=c[(h&3)<<4|k>>4];k=c[(k&15)<<2|m>>6];m=c[m&63];d[g++]=n+h+k+m}n=0;m=e;switch(b.length-f){case 2:n=b[f+1],m=c[(n&15)<<2]||e;case 1:b=b[f],d[g]=c[b>>2]+c[(b&3)<<4|n>>4]+m+e}b=d.join("")}a=a.g=b}return a}return}return a}var Id;function Kd(a){a=a.l;return Hd(a,a[C]|0,Jd)};var Ld,Md;function Nd(a){switch(typeof a){case "boolean":return Ld||(Ld=[0,void 0,!0]);case "number":return a>0?void 0:a===0?Md||(Md=[0,void 0]):[-a,void 0];case "string":return[0,a];case "object":return a}}function Od(a,b){return F(a,b[0],b[1])}
function F(a,b,c,d){d=d===void 0?0:d;if(a==null){var e=32;c?(a=[c],e|=128):a=[];b&&(e=e&-16760833|(b&1023)<<14)}else{if(!Array.isArray(a))throw Error("narr");e=a[C]|0;if(Da&&1&e)throw Error("rfarr");2048&e&&!(2&e)&&Pd();if(e&256)throw Error("farr");if(e&64)return(e|d)!==e&&E(a,e|d),a;if(c&&(e|=128,c!==a[0]))throw Error("mid");a:{c=a;e|=64;var f=c.length;if(f){var g=f-1,h=c[g];if(h!=null&&typeof h==="object"&&h.constructor===Object){b=e&128?0:-1;g-=b;if(g>=1024)throw Error("pvtlmt");for(var k in h)f=
+k,f<g&&(c[f+b]=h[k],delete h[k]);e=e&-16760833|(g&1023)<<14;break a}}if(b){k=Math.max(b,f-(e&128?0:-1));if(k>1024)throw Error("spvt");e=e&-16760833|(k&1023)<<14}}}E(a,e|64|d);return a}function Pd(){if(Da)throw Error("carr");fd(Qc,5)};function Qd(a,b){if(typeof a!=="object")return a;if(Array.isArray(a)){var c=a[C]|0;a.length===0&&c&1?a=void 0:c&2||(!b||4096&c||16&c?a=Rd(a,c,!1,b&&!(c&16)):(Wc(a,34),c&4&&Object.freeze(a)));return a}if(a!=null&&a[Rc]===Yc)return b=a.l,c=b[C]|0,Zc(a,c)?a:Sd(a,b,c)?Td(a,b):Rd(b,c);if(a instanceof Ob)return a}function Td(a,b,c){a=new a.constructor(b);c&&(a.g=$c);a.h=$c;return a}function Rd(a,b,c,d){d!=null||(d=!!(34&b));a=Hd(a,b,Qd,d);d=32;c&&(d|=2);b=b&16769217|d;E(a,b);return a}
function Ud(a){if(a.g!==$c)return!1;var b=a.l;b=Rd(b,b[C]|0);Wc(b,2048);a.l=b;a.g=void 0;a.h=void 0;return!0}function Vd(a){if(!Ud(a)&&Zc(a,a.l[C]|0))throw Error();}function Wd(a,b){b===void 0&&(b=a[C]|0);b&32&&!(b&4096)&&E(a,b|4096)}function Sd(a,b,c){return c&2?!0:c&32&&!(c&4096)?(E(b,c|2),a.g=$c,!0):!1};function Xd(a,b,c){a=Yd(a.l,b,void 0,c);if(a!==null)return a}function Yd(a,b,c,d){if(b===-1)return null;var e=b+(c?0:-1),f=a.length-1;if(!(f<1+(c?0:-1))){if(e>=f){var g=a[f];if(g!=null&&typeof g==="object"&&g.constructor===Object){c=g[b];var h=!0}else if(e===f)c=g;else return}else c=a[e];if(d&&c!=null){d=d(c);if(d==null)return d;if(!Object.is(d,c))return h?g[b]=d:a[e]=d,d}return c}}function Zd(a,b,c){Vd(a);var d=a.l;H(d,d[C]|0,b,c);return a}
function H(a,b,c,d,e){var f=c+(e?0:-1),g=a.length-1;if(g>=1+(e?0:-1)&&f>=g){var h=a[g];if(h!=null&&typeof h==="object"&&h.constructor===Object)return h[c]=d,b}if(f<=g)return a[f]=d,b;if(d!==void 0){var k;g=((k=b)!=null?k:b=a[C]|0)>>14&1023||536870912;c>=g?d!=null&&(f={},a[g+(e?0:-1)]=(f[c]=d,f)):a[f]=d}return b}function $d(a,b){return ae(a,a[C]|0,b)}function be(a){return!!(2&a)&&!!(4&a)||!!(256&a)}
function ce(a){return a==null?a:typeof a==="string"?a?new Ob(a,Nb):Qb():a.constructor===Ob?a:Hb&&a!=null&&a instanceof Uint8Array?a.length?new Ob(new Uint8Array(a),Nb):Qb():void 0}function ae(a,b,c){if(b&2)throw Error();var d=cd(b);var e=Yd(a,c,d);e=Array.isArray(e)?e:Uc;var f=e===Uc?7:e[C]|0;var g=f;2&b&&(g|=2);g|=1;if(2&g||be(g)||16&g)g===f||be(g)||E(e,g),e=gd(e),f=0,g=de(g,b),H(a,b,c,e,d);g&=-13;g!==f&&E(e,g);return e}
function ee(a,b,c,d){Vd(a);var e=a.l,f=e[C]|0;if(d==null){var g=fe(e);if(ge(g,e,f,c)===b)g.set(c,0);else return a}else f=he(e,f,c,b);H(e,f,b,d);return a}function ie(a,b,c,d){var e=a[C]|0,f=cd(e);e=he(a,e,c,b,f);H(a,e,b,d,f)}function fe(a){if(Jc){var b;return(b=a[Mc])!=null?b:a[Mc]=new Map}if(Mc in a)return a[Mc];b=new Map;Object.defineProperty(a,Mc,{value:b});return b}function he(a,b,c,d,e){var f=fe(a),g=ge(f,a,b,c,e);g!==d&&(g&&(b=H(a,b,g,void 0,e)),f.set(c,d));return b}
function ge(a,b,c,d,e){var f=a.get(d);if(f!=null)return f;for(var g=f=0;g<d.length;g++){var h=d[g];Yd(b,h,e)!=null&&(f!==0&&(c=H(b,c,f,void 0,e)),f=h)}a.set(d,f);return f}function je(a,b,c){var d=a[C]|0,e=cd(d),f=Yd(a,c,e);if(f!=null&&f[Rc]===Yc){if(!Zc(f))return Ud(f),f.l;var g=f.l}else Array.isArray(f)&&(g=f);if(g){var h=g[C]|0;h&2&&(g=Rd(g,h))}g=Od(g,b);g!==f&&H(a,d,c,g,e);return g}
function ke(a,b){var c=le,d=!1,e=Yd(a,4,void 0,function(f){if(f!=null&&f[Rc]===Yc)var g=f;else if(Array.isArray(f)){g=f[C]|0;var h=g|b&32;h|=b&2;h!==g&&E(f,h);g=new c(f)}else g=void 0;d=g!==f&&g!=null;return g});if(e!=null)return d&&!Zc(e)&&Wd(a,b),e}function me(a){var b=a.l,c=b[C]|0,d=ke(b,c);if(d==null)return d;c=b[C]|0;if(!Zc(a,c)){var e=d;var f=e.l,g=f[C]|0;e=Zc(e,g)?Sd(e,f,g)?Td(e,f,!0):new e.constructor(Rd(f,g,!1)):e;e!==d&&(Ud(a)&&(b=a.l,c=b[C]|0),d=e,c=H(b,c,4,d),Wd(b,c))}return d}
function ne(a){a==null&&(a=void 0);return a}function oe(a,b,c){c=ne(c);Zd(a,b,c);c&&!Zc(c)&&Wd(a.l);return a}function pe(a,b){Vd(a);var c=a.l,d=c[C]|0;if(b==null)return H(c,d,1),a;for(var e=b===Uc?7:b[C]|0,f=e,g=be(e),h=g||Object.isFrozen(b),k=!0,m=!0,n=0;n<b.length;n++){var w=b[n];g||(w=Zc(w),k&&(k=!w),m&&(m=w))}g||(e=k?13:5,e=m?e&-4097:e|4096);h&&e===f||(b=gd(b),f=0,e=de(e,d));e!==f&&E(b,e);d=H(c,d,1,b);2&e||!(4096&e||16&e)||Wd(c,d);return a}function de(a,b){return a=(2&b?a|2:a&-3)&-273};function I(a,b,c){this.l=F(a,b,c,2048)}I.prototype.toJSON=function(){var a=Kd(this);return a};I.prototype[Rc]=Yc;I.prototype.toString=function(){return this.l.toString()};function J(){function a(){throw Error();}Object.setPrototypeOf(a,a.prototype);return a}var qe=J(),re=J(),se=J(),te=J(),ue=J(),ve=J(),we=J(),xe=J(),ye=J(),ze=J();function Ae(a,b,c){this.g=a;this.h=b;a=Ba(qe);this.i=!!a&&c===a||!1}function Be(a,b){var c=c===void 0?qe:c;return new Ae(a,b,c)}function Ce(a,b,c,d,e){Hc(a,c,De(b,d),e)}var Ee=Be(function(a,b,c,d,e){if(a.g!==2)return!1;xc(a,je(b,d,c),e);return!0},Ce),Fe=Be(function(a,b,c,d,e){if(a.g!==2)return!1;xc(a,je(b,d,c),e);return!0},Ce),Ge=Symbol(),He=Symbol(),Ie=Symbol(),Je=Symbol(),Ke=Symbol(),Le,Me;
function Ne(a,b,c,d){var e=d[a];if(e)return e;e={};e.aa=d;e.O=Nd(d[0]);var f=d[1],g=1;f&&f.constructor===Object&&(e.V=f,f=d[++g],typeof f==="function"&&(e.Y=!0,Le!=null||(Le=f),Me!=null||(Me=d[g+1]),f=d[g+=2]));for(var h={};f&&Array.isArray(f)&&f.length&&typeof f[0]==="number"&&f[0]>0;){for(var k=0;k<f.length;k++)h[f[k]]=f;f=d[++g]}for(k=1;f!==void 0;){typeof f==="number"&&(k+=f,f=d[++g]);var m=void 0;if(f instanceof Ae)var n=f;else n=Ee,g--;f=void 0;if((f=n)==null?0:f.i){f=d[++g];m=d;var w=g;typeof f===
"function"&&(f=f(),m[w]=f);m=f}f=d[++g];w=k+1;typeof f==="number"&&f<0&&(w-=f,f=d[++g]);for(;k<w;k++){var y=h[k];m?c(e,k,n,m,y):b(e,k,n,y)}}return d[a]=e}function Oe(a){return Array.isArray(a)?a[0]instanceof Ae?a:[Fe,a]:[a,void 0]}function De(a,b){if(a instanceof I)return a.l;if(Array.isArray(a))return Od(a,b)};function Pe(a,b,c,d){var e=c.g;a[b]=d?function(f,g,h){return e(f,g,h,d)}:e}function Qe(a,b,c,d,e){var f=c.g,g,h;a[b]=function(k,m,n){return f(k,m,n,h||(h=Ne(He,Pe,Qe,d).O),g||(g=Re(d)),e)}}
function Re(a){var b=a[Ie];if(b!=null)return b;var c=Ne(He,Pe,Qe,a);b=c.Y?function(d,e){return Le(d,e,c)}:function(d,e){for(;vc(e)&&e.g!=4;){var f=e.i,g=c[f];if(g==null){var h=c.V;h&&(h=h[f])&&(h=Se(h),h!=null&&(g=c[f]=h))}if(g==null||!g(e,d,f)){h=e;g=h.j;wc(h);if(h.U)var k=void 0;else{var m=h.h.g-g;h.h.g=g;k=kc(h.h,m)}m=h=g=void 0;var n=d;k&&((g=(h=(m=n[Nc])!=null?m:n[Nc]=new Dd)[f])!=null?g:h[f]=[]).push(k)}}if(d=Cd(d))d.g=c.aa[Ke];return!0};a[Ie]=b;a[Ke]=Te.bind(a);return b}
function Te(a,b,c,d){var e=this[He],f=this[Ie],g=Od(void 0,e.O),h=Cd(a);if(h){var k=!1,m=e.V;if(m){e=function(G,D,T){if(T.length!==0)if(m[D])for(G=q(T),D=G.next();!D.done;D=G.next()){D=sc(D.value);try{k=!0,f(g,D)}finally{uc(D)}}else d==null||d(a,D,T)};if(b==null)Ed(h,e);else if(h!=null){var n=h[b];n&&e(h,b,n)}if(k){var w=a[C]|0;if(w&2&&w&2048&&(c==null||!c.fa))throw Error();var y=cd(w),A=function(G,D){if(Yd(a,G,y)!=null)switch(c==null?void 0:c.ea){case 1:return;default:throw Error();}D!=null&&(w=
H(a,w,G,D,y));delete h[G]};b==null?ad(g,g[C]|0,function(G,D){A(G,D)}):A(b,Yd(g,b,y))}}}}function Se(a){a=Oe(a);var b=a[0].g;if(a=a[1]){var c=Re(a),d=Ne(He,Pe,Qe,a).O;return function(e,f,g){return b(e,f,g,d,c)}}return b};function Ue(a,b,c){a[b]=c.h}function Ve(a,b,c,d){var e,f,g=c.h;a[b]=function(h,k,m){return g(h,k,m,f||(f=Ne(Ge,Ue,Ve,d).O),e||(e=We(d)))}}function We(a){var b=a[Je];if(!b){var c=Ne(Ge,Ue,Ve,a);b=function(d,e){return Xe(d,e,c)};a[Je]=b}return b}function Xe(a,b,c){ad(a,a[C]|0,function(d,e){if(e!=null){var f=Ye(c,d);f?f(b,e,d):d<500||fd(Pc,3)}});(a=Cd(a))&&Ed(a,function(d,e,f){Cc(b,b.g.end());for(d=0;d<f.length;d++)Cc(b,Tb(f[d])||new Uint8Array(0))})}
function Ye(a,b){var c=a[b];if(c)return c;if(c=a.V)if(c=c[b]){c=Oe(c);var d=c[0].h;if(c=c[1]){var e=We(c),f=Ne(Ge,Ue,Ve,c).O;c=a.Y?Me(f,e):function(g,h,k){return d(g,h,k,f,e)}}else c=d;return a[b]=c}};function K(a,b,c){if(Array.isArray(b)){var d=b[C]|0;if(d&4)return b;for(var e=0,f=0;e<b.length;e++){var g=a(b[e]);g!=null&&(b[f++]=g)}f<e&&(b.length=f);a=d|1;c&&(a=(a|4)&-1537);a!==d&&E(b,a);c&&a&2&&Object.freeze(b);return b}}function L(a,b,c){return new Ae(a,b,c)}function M(a,b,c){return new Ae(a,b,c)}function N(a,b,c){H(a,a[C]|0,b,c,cd(a[C]|0))}
var Ze=Be(function(a,b,c,d,e){if(a.g!==2)return!1;a=xc(a,Od([void 0,void 0],d),e);a=gd(a);d=b[C]|0;e=cd(d);if(d&2)throw Error();var f=Yd(b,c,e);if(Array.isArray(f)){var g=f[C]|0;g&8192||E(f,g|=8192);if(g&2){f=gd(f);for(g=0;g<f.length;g++){var h=f[g]=gd(f[g]);if(Array.isArray(h[1])){var k=h[1];Wc(k,34);h[1]=k}}f=Xc(f);H(b,d,c,f,e)}f.push(a)}else H(b,d,c,Xc([a]),e);return!0},function(a,b,c,d,e){if(Array.isArray(b)){for(var f=0;f<b.length;f++){var g=b[f];Array.isArray(g)&&Hc(a,c,Od(g,d),e)}Xc(b)}});
function $e(a,b,c){b=rd(b);b!=null&&(B(a,c,1),a=a.g,Ya(b),z(a,v),z(a,x))}function af(a,b,c){b=rd(b);b!=null&&(B(a,c,5),a=a.g,Xa(b),z(a,v))}function bf(a,b,c){b=xd(b);if(b!=null){switch(typeof b){case "string":nb(b)}if(b!=null)switch(B(a,c,0),typeof b){case "number":a=a.g;Va(b);oc(a,v,x);break;case "bigint":c=mb(b);oc(a.g,c.h,c.g);break;default:c=nb(b),oc(a.g,c.h,c.g)}}}
function cf(a,b,c){b=yd(b);if(b!=null){switch(typeof b){case "string":jb(b)}if(b!=null)switch(B(a,c,0),typeof b){case "number":a=a.g;Va(b);oc(a,v,x);break;case "bigint":c=ib(b);oc(a.g,c.h,c.g);break;default:c=jb(b),oc(a.g,c.h,c.g)}}}function df(a,b,c){b=vd(b);b!=null&&b!=null&&(B(a,c,0),qc(a.g,b))}function ef(a,b,c){b=sd(b);b!=null&&(B(a,c,0),a.g.g.push(b?1:0))}function ff(a,b,c){b=Bd(b);b!=null&&Gc(a,c,xb(b))}function gf(a,b,c,d,e){Hc(a,c,De(b,d),e)}function hf(a,b,c){Fc(a,c,vd(b))}
function jf(a,b,c){if(a.g!==5&&a.g!==2)return!1;b=$d(b,c);a.g==2?Ac(a,ec,b):b.push(ec(a.h));return!0}function kf(a,b,c){if(a.g!==0)return!1;N(b,c,Xb(a.h,ab));return!0}function lf(a,b,c){if(a.g!==0&&a.g!==2)return!1;b=$d(b,c);a.g==2?Ac(a,Zb,b):b.push(Zb(a.h));return!0}function mf(a,b,c){if(a.g!==0&&a.g!==2)return!1;b=$d(b,c);a.g==2?Ac(a,hc,b):b.push(hc(a.h));return!0}
var nf=L(function(a,b,c){if(a.g!==1)return!1;N(b,c,fc(a.h));return!0},$e,xe),of=L(function(a,b,c,d){if(a.g!==1)return!1;ie(b,c,d,fc(a.h));return!0},$e,xe),O=L(function(a,b,c){if(a.g!==5)return!1;N(b,c,ec(a.h));return!0},af,we),pf=M(jf,function(a,b,c){b=K(rd,b,!0);if(b!=null)for(var d=0;d<b.length;d++){var e=a,f=c,g=b[d];g!=null&&(B(e,f,5),e=e.g,Xa(g),z(e,v))}},we),P=M(jf,function(a,b,c){b=K(rd,b,!0);if(b!=null&&b.length)for(B(a,c,2),pc(a.g,b.length*4),c=0;c<b.length;c++){var d=a.g;Xa(b[c]);z(d,v)}},
we),qf=L(function(a,b,c,d){if(a.g!==5)return!1;ie(b,c,d,ec(a.h));return!0},af,we),rf=L(function(a,b,c){if(Ea)return a.g!==0?a=!1:(N(b,c,cc(a.h)),a=!0),a;if(a.g!==0)return!1;N(b,c,bc(a.h));return!0},bf,ue),sf=M(function(a,b,c){if(Ea)return a.g!==0&&a.g!==2?a=!1:(b=$d(b,c),a.g==2?Ac(a,cc,b):b.push(cc(a.h)),a=!0),a;if(a.g!==0&&a.g!==2)return!1;b=$d(b,c);a.g==2?Ac(a,bc,b):b.push(bc(a.h));return!0},function(a,b,c){b=K(xd,b,!1);if(b!=null&&b.length){c=Dc(a,c);for(var d=0;d<b.length;d++){var e=b[d];switch(typeof e){case "number":var f=
a.g;Va(e);oc(f,v,x);break;case "bigint":e=mb(e);oc(a.g,e.h,e.g);break;default:e=nb(e),oc(a.g,e.h,e.g)}}Ec(a,c)}},ue),tf=L(function(a,b,c,d){if(Ea)return a.g!==0?a=!1:(ie(b,c,d,cc(a.h)),a=!0),a;if(a.g!==0)return!1;ie(b,c,d,bc(a.h));return!0},bf,ue),uf=L(function(a,b,c){if(Ea)return kf(a,b,c);if(a.g!==0)return!1;N(b,c,Xb(a.h,$a));return!0},cf,ve),vf=L(function(a,b,c){if(Ea)return kf(a,b,c);if(a.g!==0)return!1;N(b,c,Xb(a.h,Za));return!0},cf,ve),Q=L(function(a,b,c){if(a.g!==0)return!1;N(b,c,Zb(a.h));
return!0},df,te),wf=M(lf,function(a,b,c){b=K(vd,b,!0);if(b!=null)for(var d=0;d<b.length;d++){var e=a,f=c,g=b[d];g!=null&&(B(e,f,0),qc(e.g,g))}},te),xf=M(lf,function(a,b,c){b=K(vd,b,!0);if(b!=null&&b.length){c=Dc(a,c);for(var d=0;d<b.length;d++)qc(a.g,b[d]);Ec(a,c)}},te),yf=L(function(a,b,c,d){if(a.g!==0)return!1;ie(b,c,d,Zb(a.h));return!0},df,te),R=L(function(a,b,c){if(a.g!==0)return!1;N(b,c,hc(a.h));return!0},ef,re),zf=M(mf,function(a,b,c){b=K(sd,b,!0);if(b!=null)for(var d=0;d<b.length;d++){var e=
a,f=c,g=b[d];g!=null&&(B(e,f,0),e.g.g.push(g?1:0))}},re),Af=M(mf,function(a,b,c){b=K(sd,b,!0);if(b!=null&&b.length)for(B(a,c,2),pc(a.g,b.length),c=0;c<b.length;c++)a.g.g.push(b[c]?1:0)},re),Bf=L(function(a,b,c,d){if(a.g!==0)return!1;ie(b,c,d,hc(a.h));return!0},ef,re),S=L(function(a,b,c){if(a.g!==2)return!1;N(b,c,yc(a));return!0},ff,se),Cf=L(function(a,b,c,d){if(a.g!==2)return!1;ie(b,c,d,yc(a));return!0},ff,se),U=M(function(a,b,c){if(a.g!==2)return!1;a=yc(a);ae(b,b[C]|0,c).push(a);return!0},function(a,
b,c){b=K(Bd,b,!0);if(b!=null)for(var d=0;d<b.length;d++){var e=a,f=c,g=b[d];g!=null&&Gc(e,f,xb(g))}},se),V,Df=void 0;Df=Df===void 0?qe:Df;V=new Ae(function(a,b,c,d,e){if(a.g!==2)return!1;d=Od(void 0,d);ae(b,b[C]|0,c).push(d);xc(a,d,e);return!0},function(a,b,c,d,e){if(Array.isArray(b)){for(var f=0;f<b.length;f++)gf(a,b[f],c,d,e);a=b[C]|0;a&1||E(b,a|1)}},Df);
var W=Be(function(a,b,c,d,e,f){if(a.g!==2)return!1;var g=b[C]|0;he(b,g,f,c,cd(g));b=je(b,d,c);xc(a,b,e);return!0},gf),Ef=L(function(a,b,c){if(a.g!==2)return!1;N(b,c,zc(a));return!0},function(a,b,c){b=zd(b);b!=null&&Gc(a,c,Vb(b,!0).buffer)},ye),X=L(function(a,b,c){if(a.g!==0)return!1;N(b,c,$b(a.h));return!0},function(a,b,c){b=wd(b);b!=null&&b!=null&&(B(a,c,0),pc(a.g,b))},J()),Y=L(function(a,b,c){if(a.g!==0)return!1;N(b,c,Zb(a.h));return!0},hf,ze),Ff=M(function(a,b,c){if(a.g!==0&&a.g!==2)return!1;b=
$d(b,c);a.g==2?Ac(a,ic,b):b.push(Zb(a.h));return!0},function(a,b,c){b=K(vd,b,!0);if(b!=null)for(var d=0;d<b.length;d++)Fc(a,c,b[d])},ze),Gf=L(function(a,b,c,d){if(a.g!==0)return!1;ie(b,c,d,Zb(a.h));return!0},hf,ze),Hf=M(function(a,b,c){if(a.g!==0&&a.g!==2)return!1;b=$d(b,c);a.g==2?Ac(a,ac,b):b.push(ac(a.h));return!0},function(a,b,c){b=K(vd,b,!0);if(b!=null)for(var d=0;d<b.length;d++){var e=a,f=c,g=b[d];g!=null&&(B(e,f,0),pc(e.g,(g<<1^g>>31)>>>0))}},J()),If=[!0,S,Q],Jf=[!0,S,R],Kf=[!0,S,S];function Lf(a){return function(b){var c=new Bc;Xe(b.l,c,Ne(Ge,Ue,Ve,a));Cc(c,c.g.end());b=new Uint8Array(c.h);for(var d=c.i,e=d.length,f=0,g=0;g<e;g++){var h=d[g];b.set(h,f);f+=h.length}c.i=[b];return b}};var Mf=[0,L(function(a,b,c){if(Ea){if(a.g!==1)b=!1;else{var d=a.h;a=dc(d);d=dc(d);N(b,c,ab(a,d));b=!0}return b}if(a.g!==1)return!1;d=a.h;a=dc(d);d=dc(d);N(b,c,$a(a,d));return!0},function(a,b,c){b=yd(b);if(b!=null)switch(Ic(b),B(a,c,1),a=a.g,Ic(b),typeof b){case "number":b<0?(c=-b,c=hb(new gb(c&4294967295,c/4294967296)),b=c.g,z(a,c.h),z(a,b)):(Ua(b),z(a,v),z(a,x));break;case "bigint":c=b<BigInt(0)?hb(ib(-b)):ib(b);b=c.g;z(a,c.h);z(a,b);break;default:c=b.length&&b[0]==="-"?hb(jb(b.substring(1))):jb(b),
b=c.g,z(a,c.h),z(a,b)}},J()),-1];var Nf=[0,L(function(a,b,c){if(a.g!==5)return!1;a=a.h;var d=a.h,e=a.g,f=d[e],g=d[e+1],h=d[e+2];d=d[e+3];Yb(a,a.g+4);N(b,c,f<<0|g<<8|h<<16|d<<24);return!0},function(a,b,c){b=vd(b);b!=null&&(B(a,c,5),a=a.g,a.g.push(b>>>0&255),a.g.push(b>>>8&255),a.g.push(b>>>16&255),a.g.push(b>>>24&255))},J()),-1];var Of=[0,Y,-1,rf,S,Nf,-1,O,Q,Y,Mf,S,Y,-1,[0,Nf,-1],Q,vf,Mf,O,[0,1,Q,-4,nf,[0,O,-1,Q],S,O,V,[0,Y,Q],Q,-1,Y,-2,O,-1,Y,O,Y,Q,[0,3,Q,-1,4,M(function(a,b,c){if(a.g!==2)return!1;a=zc(a);ae(b,b[C]|0,c).push(a);return!0},function(a,b,c){b=K(zd,b,!1);if(b!=null)for(var d=0;d<b.length;d++){var e=a,f=c,g=b[d];g!=null&&Gc(e,f,Vb(g,!0).buffer)}},ye)],nf,X,[0,Y,-1,S]],S,Ff,V,[0,Mf,V,[0,S,Y],O,Y,-1],1,V,[0,vf,-1,X],Y,Mf];var Pf=[0,rf,[0,O,S,Q,S,Q,wf,rf,S,Q,S,-1,O,Q,O],Ef,[0,M(function(a,b,c){if(a.g!==1&&a.g!==2)return!1;b=$d(b,c);if(a.g==2){c=a.h;a=$b(a.h)/8;var d=c.g,e=8*a;if(d+e>c.i)throw Error();var f=c.h;d+=f.byteOffset;mc===void 0&&(mc=(new Uint16Array((new Uint8Array([1,2])).buffer))[0]==513);if(mc)for(c.g+=e,c=new Float64Array(f.buffer.slice(d,d+e)),a=0;a<c.length;a++)b.push(c[a]);else for(e=0;e<a;e++)b.push(fc(c))}else b.push(fc(a.h));return!0},function(a,b,c){b=K(rd,b,!0);if(b!=null)for(var d=0;d<b.length;d++){var e=
a,f=c,g=b[d];g!=null&&(B(e,f,1),e=e.g,Ya(g),z(e,v),z(e,x))}},xe),-1]];function le(a){this.l=F(a,void 0,void 0,2048)}p(le,I);function Qf(a){a=Xd(a,1,ce);return a==null?Qb():a}function Rf(a){var b=16E3;b=b===void 0?0:b;a=vd(Xd(a,2));return a!=null?a:b};function Sf(a){this.l=F(a,void 0,void 0,2048)}p(Sf,I);function Tf(a){this.l=F(a,void 0,void 0,2048)}p(Tf,I);var Uf=[0,Ef,Q];var Vf=[0,[1,2,3,4],Cf,Gf,W,[0,S,Y],Gf];var Wf=[0,S,-2,3,O,S,U,Y,-1,V,Vf,S,-2];var Xf=[0,Q,-3];var Yf=[0,[1,2,3,4],Bf,-1,Cf,-1];var ag=[0,S,-1,1,S,-1,6,U,[0,X,S,X,Q,X,-4,O,X,O,-1],R,U,-1];var Z=[0,Y,-5];var bg=[0,[0,S,-5,R,U,Z],S,-7,R,S,U,Z];var cg=[0,U,1,Y,-1,S];var dg=[0,S,-2,Z,S];var eg=[0,S,-1,R,S,U,Z];var fg=[0,V,[0,S,-1],S,R,S];var gg=[0,S,-2,Z];var hg=[0,S,-3,Q,S,R,S,-1,R,S,U,Z,S,-2];var ig=[0,R,S,-3,Q,S,R,S,U,Z];var jg=[0,S,-3,Q,S,-3,R,S,U,Z];var kg=[0,S,Q,Y,S];var lg=[0,S,-2,Q,S,R,S,R,U,Z];var mg=[0,S,-2,R];var ng=[0,ig,lg,eg,S,Q,S,R,S,U,Z];var og=[0,ig,rf,S,Q,S,R,S,U,Z,S];var pg=[0,S,-1,R,S,U,Z,R];var qg=[0,S,Q,R];var rg=[0,S,U,S,Q,S,R,S,U,Z];var sg=[0,Q,-2,R,S,Q,S,Q,S,R,S,U,Z,R];var tg=[0,Y,-1];var ug=[0,O,-1];var vg=[0,V,[0,O,-2],O,-1,Q,V,[0,Q,Y,Q,Y,X,Y,-1,V,ug,[0,O,-1],[0,V,ug,O,Y],[0,V,ug,Y]],O];var wg=[0,O,-2];var xg=[-11,{},Xf,S,[0,Af,xf,P,U,V,[0,P],[0,P]],P,S,-1,[0,wg],S,[0,P,-1,V,[0,Y,Q]],-1];var yg=[0,Xf,[0,R,O,P,-1],Q,[0,P]];var zg=[0,Q,-2];var Ag=[0,Y,[0,wf,sf]];var Bg=[0,Y,[0,wf,U]];var Cg=[0,Q,-1,Y,Q];var Dg=[0,P,xf];var Eg=[0,P,xf,S];var Fg=[0,[0,uf,Y,R]];var Gg=[0,Q,-2,S];var Hg=[0,Y];var Jg=[-15,{},V,[-45,{},[1,3,4,5,6,7,8,9,10,11,12,13,14,15,16,18,19,21,25,32,36,37,41],Cf,S,W,eg,W,pg,W,ig,W,lg,W,sg,W,ng,W,hg,W,bg,W,rg,W,og,W,jg,W,fg,Cf,-1,V,mg,Cf,-1,vg,qf,[0,R,-1,Y,tg,R,-1,O,R,U,Cg,Y,-1],Of,R,W,[0,S,-1],V,[0,S,-1],[0,U,R],Z,Y,Hg,R,W,qg,S,U,S,W,gg,W,dg,S,-1,R,W,kg,R,Gg,S],V,[0,S,V,[0,S,-1,Y],V,[0,S,-1],S,Y,[0,Y,-3],U,R,S],4,Hg,O,R,function(){return Ig},S,Fg,R,[0,R,-1]],Ig=[0,V,function(){return Jg},-1];var Kg=function(a,b){return function(c,d){var e={S:!0};d&&Object.assign(e,d);c=sc(c,void 0,void 0,e);try{var f=new a,g=f.l;Re(b)(g,c);var h=f}finally{uc(c)}return h}}(Tf,[0,Y,2,Uf,Y,[-500,{},vf,S,Jg,-1,1,[0,Y,Q,-1,O],[0,S,-5,Q,S,1,R,-1,S,Y,V,Wf,S],rf,-2,89,[-5,{},V,[-75,{},Xf,X,-1,S,Y,S,-2,R,O,Y,S,R,-1,5,eg,pg,S,ig,lg,sg,ng,ig,hg,bg,rg,og,jg,S,-1,gg,S,dg,1,fg,kg,[0,S,-1],V,mg,7,ag,1,S,R,S,R,qg,S,R,S,-2,Yf,S,R,O,U,1,S,R,1,S,cg,Y,R],V,[-71,{},Xf,Y,S,-1,R,1,S,Y,ag,O,Y,R,Ff,S,tg,1,Q,R,1,S,Y,O,[0,[0,O,
-2],[0,O,-2]],[0,Y,-2],25,vg,S,3,R,-1,1,R,S,2,R,Yf,S,Y,O,S,-1,1,S],V,[-11,{},Xf,S,Y,5,[0,Q,-3],S],V,[-12,{},Xf,S,R,O,-1,[0,O,-6,V,[0,S,Y,O]],pf,Q,-1,S,[0,[0,Q,-3],V,[0,S,O]]]],1,[0,3,V,[0,V,zg,zg],R],3,Cg,Y,-1,1,[-12,{},Cg,Y,-1,[0,Y,2,Y,-1],Y,-1,S,3,[0,R,-2]],39,[0,[0,Q,-2,xf,-2],Bg,-2,Ag,Bg,-2,Ag,-5],49,[-3,{},[0,V,xg,[0,V,[0,S,V,[0,Q,O,V,[0,Q,O,-1,Q],R],V,[0,Q,O],R,-2]]],V,[0,Q,V,[0,Xf,[-10,{},Q,-2,X,[0,X,-2,O,-8,pf,-5,Hf,-1],Ff,Q,-2],wg,O,-2,V,[0,Y,pf]]]],[-3,{},[0,V,xg],V,[-6,{},V,yg,V,wg,wf,
zf,xf]],48,[0,[0,V,yg,Pf],[0,O,X,-1,O,X]],49,Uf,599,[-1,{}],R,[0,O,-2,Q],[-3,{},V,[-7,{},X,-1,R,V,[0,[1,2,3,4],W,[-5,{},Y,S,-1,R],W,[0],W,[0],W,[0]],O,X],X],Dg,V,Eg]]);var Lg=Lf(Wf);function Mg(a){this.l=F(a,void 0,void 0,2048)}p(Mg,I);var Ng=[1,4];function Og(a){this.l=F(a,11,void 0,2048)}p(Og,I);var Pg=[0,Q,Ef,Y];var Qg=[-11,{},[0,V,[0,Y,1,Y],Ff,Of,U,V,[0,S,Y,O,Y],1,Y,-1,R],[0,S,-3,O,[0,Q,S],Ff,-1],[0,Ng,qf,[0,Y],[0,2,Y],Gf,[0,R,-1],O,Y,-2],[0,1,O,V,[0,S,-1],Ff,Fg,Q],cg,[-1,{}],[0,[1,3],W,[0,[3,4],V,Vf,-1,yf,Bf,V,Vf],S,Cf],[0,[1,2,3,4,5,6,7,8,9,10,11],Gf,-10],[0,[1,2],[6],[3,4,5],W,Pg,W,Dg,W,Pg,W,Dg,W,[0,P],W,[0,Q,-1,R,O,-1]],[0,[1],W,Dg,V,Eg,Pg]];var Rg=[-3,{},S,Qg];function Sg(a){this.l=F(a,void 0,void 0,2048)}p(Sg,I);function Tg(a){this.l=F(a,5,void 0,2048)}p(Tg,I);function Ug(a){this.l=F(a,void 0,void 0,2048)}p(Ug,I);var Vg=[2,3,4];var Wg=[0,S,-2];var Xg=[0,[3,4],S,-1,tf,of,Q,-1,S,-1];var Yg=[0,Vg,Q,W,[-5,{},V,[0,[100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120],Q,S,-1,Qg,V,[0,[4,5],Q,S,-1,Gf,Cf,S,Qg,Y],S,-1,Gg,R,90,Cf,W,[0,S,Y,[0,Y,O,Y]],W,[0,S],W,[0,S,Q],W,[0,S,Y],W,[0,S,-1],W,[0,S,Y],W,Xg,W,[0,1,S],W,Wg,W,[0,U,Y],W,[0,[5,6,7],Q,-2,S,Gf,-1,yf],W,[0,[5,6],Q,-3,Gf,yf],W,[0,[1,2],[4,5,6],W,Xg,W,Wg,S,Gf,-1,yf],W,[0,[3,4],[8,9,10],Q,-1,yf,Cf,Q,Y,S,Gf,-1,yf],W,[0,S,U,S],W,[0,[4,5,6],Xg,S,1,Gf,-1,yf],W,[0,S,-3,Q,S,-2],W,[0,S,Y],W,[0,V,[0,S,-1],S,
R],W,[0,S,-1]],Qg,V,[0,Q,-1,Qg],R],W,Rg,W,[0,[1,2],W,Pg,W,[0,S]]];var Zg=[0,Ze,Jf,Ze,If,Ze,Kf];function $g(a){this.l=F(a,4,void 0,2048)}p($g,I);var ah=[-4,{},V,Yg,Qg,Zg];function bh(a){this.l=F(a,3,void 0,2048)}p(bh,I);var ch=Lf([-3,{},V,Jg,ah]);function dh(a){a=a===void 0?new AudioContext({sampleRate:24E3}):a;this.h=!1;this.o=[];this.T={};this.M={};this.D={};this.N={};this.C={};this.Z=new TextEncoder;this.W="";this.I=null;this.J=0;this.K=[];this.H=this.u=this.B=this.j=!1;this.v=[];this.L=[];this.A=[];this.i=a;this.G=this.i.createGain()}aa=dh.prototype;
aa.init=function(a){var b=this;return t(function(c){switch(c.g){case 1:if(b.h)return c.return();b.h=!0;b.extensionId=a;return c.h(loadWasmTtsBindings(),2);case 2:return b.g=c.j,c.h(eh(b),3);case 3:return c.h(fh(b),4);case 4:return c.return(gh(b))}})};aa.onLanguageStatusRequest=function(a){var b=this,c,d;return t(function(e){return e.g==1?b.h?e.F(2):e.h(b.init(b.extensionId),2):e.g!=4?(c="offscreenLanguageStatusResponse",d=a,e.h(hh(b,a),4)):e.return({type:c,lang:d,status:e.j})})};
aa.onInstallLanguageRequest=function(a){var b=this,c,d;return t(function(e){return e.g==1?b.h?e.F(2):e.h(b.init(b.extensionId),2):e.g!=4?(c="offscreenLanguageStatusResponse",d=a,e.h(ih(b,a),4)):e.return({type:c,lang:d,status:e.j})})};aa.onUninstallLanguageRequest=function(a){var b=this,c;return t(function(d){if(d.g==1)return b.h?d.F(2):d.h(b.init(b.extensionId),2);if(d.g!=4)return d.h(jh(b,a),4);(c=d.j)&&kh(b);return d.return({type:"offscreenLanguageStatusResponse",lang:a,status:"notInstalled"})})};
function jh(a,b){var c,d,e,f,g,h;return t(function(k){switch(k.g){case 1:c=lh(a,b),d=!1,e=q(c),f=e.next();case 2:if(f.done){k.F(4);break}g=f.value;mh(a,g);if(!g.remote||g.unloaded){k.F(3);break}h="/voices/"+g.fileId;k.A(5);return k.h(nh(a,h),7);case 7:d=!0;k.B(3);break;case 5:k.v();case 3:f=e.next();k.F(2);break;case 4:return k.return(d)}})}
aa.onStop=function(a){var b=this,c;return t(function(d){if(!b.h)return d.return();oh(b);b.j=!1;b.B=!1;b.u=a;b.m&&(c={command:"clearBuffers"},b.m.port.postMessage(c),b.m.disconnect());for(ph(b);b.L.length>0;)window.clearTimeout(b.L.pop());b.v=[];b.K.length=0;b.I=null;b.J=0;d.C()})};aa.onPause=function(){var a=this;return t(function(b){if(b.g==1){if(!a.h)return b.return();ph(a);a.u=!0;return b.h(a.i.suspend(),2)}a.j=!1;b.C()})};
aa.onResume=function(){var a=this;return t(function(b){if(b.g==1){if(!a.h||a.j)return b.return();a.u=!1;return a.B?b.h(a.i.resume(),2):(a.A.length===0&&qh(a),b.return(rh(a)))}a.j=!0;sh(a);b.C()})};
aa.onSpeak=function(a,b){var c=this,d,e,f,g,h;return t(function(k){switch(k.g){case 1:return c.u=!1,k.h(c.init(c.extensionId),2);case 2:if(!c.g)throw Error("WASM module not initialized.");return b.voiceName?k.h(c.onStop(!1),3):k.return();case 3:c.utterance=a;d=b.voiceName;if(c.W===d){k.F(4);break}k.A(5);return k.h(th(c,d,!1),7);case 7:e=c.D[d];if(!e)throw Error("Invalid voice name: "+b.voiceName);f=["/voices",e].join("/");g=[f,"pipeline.pb"].join("/");if(c.g){var m=uh(c,g);var n=uh(c,f),w=c.g._GoogleTtsInit(m,
n);c.g._free(n);c.g._free(m);m=w===1}else m=!1;if(!m)throw Error("Failed to initialize pipeline "+g);k.B(4);break;case 5:return k.v(),k.return(Promise.reject(Error("Voice is not available")));case 4:c.W=d;var y=b.lang;c.extensionId&&y&&chrome.runtime.sendMessage(c.extensionId,{type:"languageUsed",language:y});try{if(y=d,c.g&&a.length){var A=new Tg,G=new Sg;var D=Zd(G,2,Ad(a));var T=pe(A,[D]);var Bh=new Mg,Sb=b.rate;var Ch=ee(Bh,1,Ng,qd(!Sb||Sb<.1||Sb>10?1:Sb));var Zf=b.pitch;m=Zd(Ch,6,qd(Zf?Math.pow(2,
(Zf-1)*20/12):1));b.volume!==void 0&&b.volume>=0&&(c.G.gain.value=Math.min(Math.max(b.volume,0),1));n=new $g;w=new Ug;A=T;A=ne(A);ee(w,2,Vg,A);A&&!Zc(A)&&Wd(w.l);var Dh=pe(n,[w]);var Eh=new Og;var Fh=oe(Eh,3,m);var Gh=oe(Dh,2,Fh);var Hh=new bh;var Ih=oe(Hh,2,Gh);var hd=Array.from(new Uint8Array(ch(Ih))),Jh=c.N[y],Kh=new Sf;var Lh=Zd(Kh,1,Ad(Jh));var id=Lg(Lh),jd=c.g._malloc(hd.length);c.g.HEAPU8.set(hd,jd);var kd=c.g._malloc(id.length);c.g.HEAPU8.set(id,kd);var Mh=c.g._GoogleTtsInitBuffered(jd,kd,
hd.length,id.length);c.g._free(jd);c.g._free(kd);if(!Mh)throw Error("Failed to initialize buffered synthesis.");qh(c)}}catch($f){return h=$f instanceof Error?$f.message:"",k.return(Promise.reject(Error("Synthesis failed with "+h)))}k.C()}})};
function gh(a){return a.i.audioWorklet.addModule("../streaming_worklet_processor.js").then(function(){a.m=new AudioWorkletNode(a.i,"streaming-worklet-processor");a.m.port.onmessage=function(b){a.utterance&&!a.H&&b.data.type==="empty"&&(vh(a,{type:"end",charIndex:a.utterance.length}),a.onStop(!1))};a.G.connect(a.i.destination)})}function uh(a,b){b=a.Z.encode(b+"\x00");var c=a.g._malloc(b.length);a.g.HEAPU8.set(b,c);return c}
function qh(a){var b=setTimeout(function(){a.H=!0;var c=a.g,d=c._GoogleTtsReadBuffered();if(d===-1)vh(a,{type:"error"}),oh(a);else{for(var e=c._GoogleTtsGetTimepointsCount(),f=0;f<e;f++)wh(a,{audioDeltaMillis:c._GoogleTtsGetTimepointsTimeInSecsAtIndex(f)*1E3,charIndex:Number(c._GoogleTtsGetTimepointsCharIndexAtIndex(f)),length:Number(c._GoogleTtsGetTimepointsCharLengthAtIndex(f))});f=c._GoogleTtsGetEventBufferPtr();e=c._GoogleTtsGetEventBufferLen();c=new Uint8Array(c.HEAPU8.buffer,f,e);c=Kg(c.slice(0,
e));d=d===0;e=c.l;ke(e,e[C]|0)!==void 0?xh(a,c,d):yh(a,null);d?oh(a):qh(a)}},0);a.A.push(b)}function oh(a){a.H=!1;a.g._GoogleTtsFinalizeBuffered()}function ph(a){for(;a.A.length>0;)window.clearTimeout(a.A.pop())}function wh(a,b){var c=b.audioDeltaMillis,d=b.charIndex,e=b.length;d<0||c<=0||(a.j?c<-100||(c<2?vh(a,{type:"word",charIndex:d,length:e}):(c=window.setTimeout(function(){a.j?vh(a,{type:"word",charIndex:d,length:e}):a.v.push(b)},c),a.L.push(c))):a.v.push(b))}
function sh(a){var b=a.v;a.v=[];b=q(b);for(var c=b.next();!c.done;c=b.next())wh(a,c.value)}function xh(a,b,c){if(Rf(me(b))===24E3){var d;b=(d=Qf(me(b)))==null?void 0:new Uint8Array(Tb(d)||0);d=new Uint8Array(b);d=new Int16Array(d.buffer);d=Float32Array.from(d,function(e){return e/32768});zh(a,d,c)}}
function zh(a,b,c){for(var d=a.I,e=a.J,f=0,g=b.length;f<g;){var h=Math.min(128-e,g-f);d||(d=new Float32Array(128));d.set(b.subarray(f,f+h),e);f+=h;e+=h;e===128&&(yh(a,d),e=0,d=null)}e!==0&&(c?yh(a,d):(a.I=d,a.J=e))}function yh(a,b){b&&a.K.push(b);if(a.m)for(;b=a.K.shift();)a.m.port.postMessage({command:"addBuffer",buffer:b}),a.B||a.u||rh(a)}function rh(a){return t(function(b){if(b.g==1)return a.m.connect(a.G),b.h(a.i.resume(),2);a.j=!0;a.B=!0;vh(a,{type:"start",charIndex:0});sh(a);b.C()})}
function hh(a,b){return t(function(c){return c.return(Ah(a,b,!1))})}function ih(a,b){return t(function(c){return c.return(Ah(a,b,!0))})}function Ah(a,b,c){var d,e,f;return t(function(g){switch(g.g){case 1:return d=lh(a,b),e=d.map(function(h){return th(a,h.speakers[0].name,c)}),g.A(2),g.h(Promise.all(e),4);case 4:f="installed";c&&kh(a);g.B(3);break;case 2:g.v(),f=c?"failed":"notInstalled";case 3:return g.return(f)}})}
function lh(a,b){var c=b.toLowerCase();return c.includes("-")?a.o.filter(function(d){var e;return((e=d.language)==null?void 0:e.toLowerCase())===c}):a.o.filter(function(d){var e;return((e=d.language)==null?void 0:e.split("-")[0])===c})}
function Nh(a,b,c){var d,e,f,g,h,k,m,n,w,y;return t(function(A){if(!a.C[b])return A.return(Promise.resolve());d=a.C[b];f=q(Object.entries(a.M));for(g=f.next();!g.done;g=f.next())if(h=g.value,k=q(h),m=k.next().value,n=k.next().value,w=m,y=n,d===y){e=w;break}return e?A.return(th(a,e,c)):A.return(Promise.reject(Error("No multivoice found for: "+b)))})}
function th(a,b,c){var d,e,f,g,h,k;return t(function(m){switch(m.g){case 1:if(!a.g)return m.return(Promise.reject(Error("WASM module not initialized.")));m.A(2);return m.h(Nh(a,b,c),4);case 4:m.B(3);break;case 2:return d=m.v(),m.return(Promise.reject(Error(""+d)));case 3:e=a.D[b];if(!e)return m.return(Promise.reject(Error("Invalid voice name: "+b)));f=["/voices",e].join("/");g=[f,"pipeline.pb"].join("/");try{if(h=a.g.FS.stat(g))return m.return(Promise.resolve())}catch(n){}k=a.T[b];return c||k.indexOf("http")!==
0?m.return(fetch(k).then(function(n){return n.ok?n.arrayBuffer():Promise.reject(Error("Failed to fetch voice from url: "+k))}).then(function(n){if(!n)return Promise.reject(Error("Failed to fetch voice from url: "+k));if(!Oh(a,e,n))return Promise.reject(Error("Failed to validate voice data: "+e));try{a.g.FS.stat(f)}catch(G){a.g.FS.mkdir(f)}a.g.FS.stat(f);var w=uh(a,f),y=new Uint8Array(n),A=a.g._malloc(y.length);a.g.HEAPU8.set(y,A);n=a.g._GoogleTtsInstallVoice(w,A,n.byteLength);a.g._free(w);a.g._free(A);
return n!==1?Promise.reject(Error("Failed to install voice.")):new Promise(function(G,D){a.g.FS.syncfs(!1,function(T){T?D(T):G()})})})):m.return(Promise.reject(Error("Not downloading remote voice because caller did not request it.")))}})}function vh(a,b){a.extensionId&&chrome.runtime.sendMessage(a.extensionId,{type:"offscreenTtsEventResponse",event:b})}
function eh(a){var b,c;return t(function(d){if(d.g==1){if((b=a.g)==null||!b.FS)throw Error("WASM FS not ready for IDBFS setup.");try{a.g.FS.stat("/voices")}catch(e){a.g.FS.mkdir("/voices")}d.A(2);return d.h(new Promise(function(e,f){a.g.FS.mount(a.g.IDBFS,{},"/voices");a.g.FS.syncfs(!0,function(g){g?f(g):e()})}),4)}if(d.g!=2)return d.B(0);c=d.v();throw c;})}
function fh(a){var b,c,d;return t(function(e){switch(e.g){case 1:return e.A(2),e.h(fetch("voices.json"),4);case 4:b=e.j;if(!b.ok)throw Error("Failed to fetch voices.json: "+b.statusText+" ("+b.status+")");return e.h(b.json(),5);case 5:c=e.j;a.o=c;kh(a);e.B(0);break;case 2:throw d=e.v(),d;}})}
function kh(a){a.T={};a.M={};a.D={};a.N={};a.C={};for(var b={},c=q(a.o),d=c.next();!d.done;d=c.next()){d=d.value;for(var e=q(d.speakers),f=e.next();!f.done;f=e.next()){f=f.value;a.M[f.name]=d.id;a.D[f.name]=d.fileId;a.N[f.name]=f.speaker;d.dependentVoiceId&&(a.C[f.name]=d.dependentVoiceId);mh(a,d);a.T[f.name]=d.remote&&d.unloaded?d.url:"/"+d.id+".zvoice";var g=d.id.split("-");if(g.length<2)throw Error("Unexpected voice id format: "+d.id);g=g[0]+"-"+g[1].toUpperCase();d.language=g;d.remote&&d.unloaded||
(b[g]||(b[g]=[]),b[g].push(f.name))}}a.extensionId&&chrome.runtime.sendMessage(a.extensionId,{type:"offscreenVoicesResponse",voices:b})}function mh(a,b){try{a.g.FS.stat(["/voices",b.fileId].join("/")),b.unloaded=!1}catch(c){b.unloaded=!0}}
function nh(a,b){if(a.g)try{for(var c=a.g.FS.readdir(b),d=q(c),e=d.next();!e.done;e=d.next()){var f=e.value;f!=="."&&f!==".."&&a.g.FS.unlink(b+"/"+f)}a.g.FS.rmdir(b);return new Promise(function(g,h){a.g.FS.syncfs(!1,function(k){k?h(k):g()})})}catch(g){return Promise.resolve()}}function Oh(a,b,c){var d,e;return t(function(f){if(f.g==1)return f.h(Ph(c),2);d=f.j;e=a.o.find(function(g){return g.fileId===b});return f.return(e!==void 0&&e.sha256Checksum===d&&e.compressedSize===c.byteLength)})}
function Ph(a){var b,c,d,e;return t(function(f){if(f.g==1)return crypto&&crypto.subtle?f.h(crypto.subtle.digest("SHA-256",a),2):f.return("");b=f.j;c="";for(d=0;d<b.byteLength;d++)e=(new Uint8Array(b))[d],c+=Number(e>>4).toString(16),c+=Number(e&15).toString(16);return f.return(c)})}ea.Object.defineProperties(dh.prototype,{voices:{configurable:!0,enumerable:!0,get:function(){return this.o}}});var Qh=new dh,Rh=null;
chrome.runtime.onMessage.addListener(function(a,b,c){Rh||(Rh=Qh.init(b.id));Rh.then(function(){switch(a.type){case "init":Qh.init(b.id);c({result:"Initialized"});break;case "getLanguageStatus":Qh.onLanguageStatusRequest(a.lang).then(c);break;case "installLanguage":Qh.onInstallLanguageRequest(a.lang).then(c);break;case "uninstallLanguage":Qh.onUninstallLanguageRequest(a.lang).then(c);break;case "removeUnusedLanguage":jh(Qh,a.lang).then(function(){c({result:"Removed "+a.lang})});break;case "speak":Qh.onSpeak(a.utterance,
a.options);c({result:"Start speaking"});break;case "stop":Qh.onStop(!0);c({result:"Stopped speech"});break;case "pause":Qh.onPause();c({result:"Paused speech"});break;case "resume":Qh.onResume(),c({result:"Resumed speech"})}});return!0});
